### ISSUE TITLE
DUVIDA: Não acho o lugar de inserir o token, onde fica ?

### ISSUE THREAD

**Issue by andrevitxr** [LouisGusta/bot_discord_olhaeleae#1]
Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (C:\xampp\htdocs\bot_discord_olhaeleae-master\node_modules\discord.js\src\client\Client.js:237:52)
    at Object.<anonymous> (C:\xampp\htdocs\bot_discord_olhaeleae-master\index.js:132:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'TOKEN_INVALID' # #

**Comment by LouisGusta** [comment]
Olá! 

Você precisa colocar o seu token id , dentro do arquivo de variáveis de ambiente! 

se não tiver o dotenv instalado,
Tente rodar no seu prompt: 
```
npm install dotenv --save
```

Crie um arquivo chamado .env e dentro dele defina o token do seu bot 
`TOKEN=YOUR_TOKEN_ID`

**Comment by andrevitxr** [comment]
consegui ligar o bot e ele conecta nos canais normalmente porem o audio não é executado, não sai som nenhum

**Comment by LouisGusta** [comment]
> consegui ligar o bot e ele conecta nos canais normalmente porem o audio não é executado, não sai som nenhum

Poderia me mandar um print do bloco de dependências do seu package.json?

**Comment by andrevitxr** [comment]
"dependencies": {
    "@discordjs/voice": "github:discordjs/voice",
    "discord.js": "^13.6.0",
    "dotenv": "^16.0.0",
    "express": "^4.17.2",
    "ffmpeg": "^0.0.4",
    "ffmpeg-static": "^4.4.1",
    "ffprobe": "^1.1.2",
    "get-audio-duration": "^3.0.0",
    "tweetnacl": "^1.0.3"
  },

**Comment by LouisGusta** [comment]
Estranho, seu console, não dá nenhum erro? 

Você gerou um novo link de convite com o bot que criou, e deu as devidas permissões para ele? Ele precisa ter permissão para falar e para conectar em algum servidor! 

A sua pasta node_modules > @dicordjs > voice 
Tem essa estrutura de arquivos? 
![image](https://user-images.githubusercontent.com/26414324/153654817-9b0b5639-d6ee-488d-98a2-29f7618becb4.png)

Fez alguma alteração na index.js? Criou o arquivo serverList.json? Também não posso subir esse arquivo para gitHub, para manter sigilo dos servidores que o bot está conectado! 

Ela tem que ter essa estrutura: 
{
 "servers" : []
}

**Comment by andrevitxr** [comment]
sim eu dei todas as permissões necessarias para o bot, porem minha pasta voice não possui essa estrutura
<img width="559" alt="aaaaa" src="https://user-images.githubusercontent.com/96602003/153669049-ce0547ea-2bc4-416c-a057-bc75ee88b721.PNG">

acho que esse talvez seja o erro porque quando dou start no bot o seguinte erro é dado

<img width="714" alt="kaka" src="https://user-images.githubusercontent.com/96602003/153669578-ee0f4014-8738-4cb3-84e1-b860bf448e15.PNG">

**Comment by LouisGusta** [comment]
Eu tive esse problema também, por algum motivo, ele não baixa os arquivos certos pro Voice ! 

Entra em outra pasta, faz a instalação somente do @discordjs/voice 
Entra nesse caminho na node_modules, pega os arquivos de lá, e joga pra esse seu, nessa pasta está faltando a pasta "dist" e a pasta "docs" 

Não sei por que isso acontece, mas só consegui resolver assim!

**Comment by LouisGusta** [comment]
Posso fechar essa questão? você conseguiu resolver ?

**Comment by LouisGusta** [comment]
Estou considerando que foi resolvido , caso precise de mais algum outra ajuda, peço que crie um novo tópico! 

Obrigado, estou fechando esse Issue !
